apiVersion: v1
kind: Service
metadata:
  name: scenario-app-service
  namespace: demo
  labels:
    app: scenario-app
spec:
  type: ClusterIP
  selector:
    app: scenario-app
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
