argocd-application.yaml 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scenario-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/Anup-Neupane/my-app.git
    targetRevision: main
    path: .
  
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: docker-credentials
    jsonPointers:
    - /data
